# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'View3DModel' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for View3DModel
  pod 'AssetImportKit'
end
