# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Firebase_HelloWorld' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase_HelloWorld
  # pod 'Firebase/Core'
  # pod 'Firebase/Database'
end
