# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'NFC_CheckIn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NFC_CheckIn
  # pod 'Firebase/Core'
  # pod 'Firebase/Database'
  # pod 'PKHUD'
end
