# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'FirebaseQuery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # pod 'Firebase/Core'
  # pod 'Firebase/Database'
  # pod 'Firebase/Analytics'
  # pod 'Firebase/Storage'
  # pod 'KRProgressHUD'
  # pod 'Kingfisher'
  # pod 'QRCodeReader.swift', '~> 10.1.0'
end
