# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'FirebaseOrder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseOrder
  # pod 'Firebase/Core'
  # pod 'Firebase/Database'
  # pod 'Firebase/Analytics'
  # pod 'Firebase/Storage'
  # pod 'KRProgressHUD'
end
